name: Plan Terraform Changes

runs:
  shell: bash

steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v1
    with:
      terraform_version: 0.14.10

  - name: Checkout Repository
    uses: actions/checkout@v2    

  - name: Initialize Terraform
    run: terraform init

  - name: Plan Terraform Changes
    run: terraform plan -out=tfplan
