name: Docker Image CI/CD

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build poll Docker image
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      working-directory: app/poll
      run: docker build -t issadocker123/docker-popeye-poll:latest-gitlab .

    - name: Build result Docker image
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      working-directory: app/result
      run: docker build -t issadocker123/docker-popeye-result:latest-gitlab .

    - name: Build worker Docker image
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      working-directory: app/worker
      run: docker build -t issadocker123/docker-popeye-worker:latest-gitlab .


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Poll Docker image to Docker Hub
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      run: docker push issadocker123/docker-popeye-poll:latest-gitlab

    - name: Push result Docker image to Docker Hub
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      run: docker push issadocker123/docker-popeye-result:latest-gitlab

    - name: Push worker Docker image to Docker Hub
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      run: docker push issadocker123/docker-popeye-worker:latest-gitlab      