name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker images
      if: github.event_name == 'push'
      steps:
          - name: Build and Push poll Docker image
            uses: docker/build-push-action@v2
            with:
              context: app/poll
              push: true
              tags: issadocker123/docker-popeye-poll:latest-gitlab

          - name: Build and Push result Docker image
            uses: docker/build-push-action@v2
            with:
              context: app/result
              push: true
              tags: issadocker123/docker-popeye-result:latest-gitlab

          - name: Build and Push worker Docker image
            uses: docker/build-push-action@v2
            with:
              context: app/worker
              push: true
              tags: issadocker123/docker-popeye-worker:latest-gitlab