name: Docker Image CI/CD

on:
  push:
    # paths:
    #   - './app/**' # Déclencher le workflow uniquement lorsque des modifications sont apportées dans le dossier 'app'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker image
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      working-directory: app/poll
      run: docker build -t issadocker123/docker-popeye-poll:latest-gitlab .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      if: github.event_name == 'push' # Ne déclencher cette étape que pour les événements de type "push"
      run: docker push issadocker123/docker-popeye-poll:latest-gitlab
