name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:     

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.10
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "."
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
